// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbMNq7AIo9SGsUSI32eFoPBBklao3RFYM',
    appId: '1:622989999412:web:80d7617d85edb91c22f961',
    messagingSenderId: '622989999412',
    projectId: 'dion-1533d',
    authDomain: 'dion-1533d.firebaseapp.com',
    storageBucket: 'dion-1533d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjFe6Yi82zENYtH-4934TJwVnWnUv9Jmg',
    appId: '1:622989999412:android:5e6d73065e146d4522f961',
    messagingSenderId: '622989999412',
    projectId: 'dion-1533d',
    storageBucket: 'dion-1533d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4OBIyBxolrXW_VTZYO5Bmqv6Ad70pdb0',
    appId: '1:622989999412:ios:cc3eb0b863d641a522f961',
    messagingSenderId: '622989999412',
    projectId: 'dion-1533d',
    storageBucket: 'dion-1533d.firebasestorage.app',
    iosBundleId: 'com.bldng.dionysos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4OBIyBxolrXW_VTZYO5Bmqv6Ad70pdb0',
    appId: '1:622989999412:ios:cc3eb0b863d641a522f961',
    messagingSenderId: '622989999412',
    projectId: 'dion-1533d',
    storageBucket: 'dion-1533d.firebasestorage.app',
    iosBundleId: 'com.bldng.dionysos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbMNq7AIo9SGsUSI32eFoPBBklao3RFYM',
    appId: '1:622989999412:web:101ceb091bdb7e8722f961',
    messagingSenderId: '622989999412',
    projectId: 'dion-1533d',
    authDomain: 'dion-1533d.firebaseapp.com',
    storageBucket: 'dion-1533d.firebasestorage.app',
  );
}
