name: Create Release on Version Change

on:
  push:
    paths:
      - 'pubspec.yaml'
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Fetch the current and previous commit
        token: ${{ secrets.PAT }}

    - name: Get Previous Version
      id: prev_version
      run: |
        prev_version=$(git show HEAD~1:pubspec.yaml | awk '/^version:/ { print $2 }')
        echo "value=$prev_version" >> $GITHUB_OUTPUT

    - name: Get Current Version
      id: current_version
      run: |
        current_version=$(awk '/^version:/ { print $2 }' pubspec.yaml)
        echo "value=$current_version" >> $GITHUB_OUTPUT

    - name: Check Version Change
      id: version_changed
      run: |
        if [ "${{ steps.prev_version.outputs.value }}" != "${{ steps.current_version.outputs.value }}" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    - run: echo "${{ steps.current_version.outputs.value }} ${{ steps.prev_version.outputs.value }}"
    - name: Create and Push Tag
      if: steps.version_changed.outputs.changed == 'true'
      run: |
        tag_name="v${{ steps.current_version.outputs.value }}"
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"
        git tag "$tag_name"
        git push origin "$tag_name"